export const COLORS = {
  mainColor: "#FA8D0E",
  primaryColor: "#FFFFFF",
  secondaryColor: "#222222",
  greyColor: "#C8C8C8",
  lightGreyColor: "#EFEFEF",
  whiteColor: "#FFFFFF",
  statusNegativeColor: "#F43529",
  kakaoColor: "#FEE500",
  RankWhitePop: "#F8F8FF",
  RankYellowPop: "#FAB913",
  RankRedPop: "#F6513B",
  RankPurplePop: "#B829FB",
  RankGoldPop: "#DCA046",
};
